// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: companyservice.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OIB     int64  `protobuf:"varint,2,opt,name=OIB,proto3" json:"OIB,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *CompanyRegisterRequest) Reset() {
	*x = CompanyRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyRegisterRequest) ProtoMessage() {}

func (x *CompanyRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companyservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyRegisterRequest.ProtoReflect.Descriptor instead.
func (*CompanyRegisterRequest) Descriptor() ([]byte, []int) {
	return file_companyservice_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyRegisterRequest) GetOIB() int64 {
	if x != nil {
		return x.OIB
	}
	return 0
}

func (x *CompanyRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisteredCompany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OIB     int64  `protobuf:"varint,2,opt,name=OIB,proto3" json:"OIB,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *RegisteredCompany) Reset() {
	*x = RegisteredCompany{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredCompany) ProtoMessage() {}

func (x *RegisteredCompany) ProtoReflect() protoreflect.Message {
	mi := &file_companyservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredCompany.ProtoReflect.Descriptor instead.
func (*RegisteredCompany) Descriptor() ([]byte, []int) {
	return file_companyservice_proto_rawDescGZIP(), []int{1}
}

func (x *RegisteredCompany) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RegisteredCompany) GetOIB() int64 {
	if x != nil {
		return x.OIB
	}
	return 0
}

func (x *RegisteredCompany) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisteredCompany) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_companyservice_proto protoreflect.FileDescriptor

var file_companyservice_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x58, 0x0a, 0x16,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x42, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x4f, 0x49, 0x42, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x63, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4f,
	0x49, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4f, 0x49, 0x42, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x61, 0x0a, 0x13, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x22, 0x00, 0x42, 0x04,
	0x5a, 0x02, 0x2f, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_companyservice_proto_rawDescOnce sync.Once
	file_companyservice_proto_rawDescData = file_companyservice_proto_rawDesc
)

func file_companyservice_proto_rawDescGZIP() []byte {
	file_companyservice_proto_rawDescOnce.Do(func() {
		file_companyservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_companyservice_proto_rawDescData)
	})
	return file_companyservice_proto_rawDescData
}

var file_companyservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_companyservice_proto_goTypes = []interface{}{
	(*CompanyRegisterRequest)(nil), // 0: main.CompanyRegisterRequest
	(*RegisteredCompany)(nil),      // 1: main.RegisteredCompany
}
var file_companyservice_proto_depIdxs = []int32{
	0, // 0: main.CompanyRegistration.registerCompany:input_type -> main.CompanyRegisterRequest
	1, // 1: main.CompanyRegistration.registerCompany:output_type -> main.RegisteredCompany
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_companyservice_proto_init() }
func file_companyservice_proto_init() {
	if File_companyservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_companyservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_companyservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredCompany); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_companyservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_companyservice_proto_goTypes,
		DependencyIndexes: file_companyservice_proto_depIdxs,
		MessageInfos:      file_companyservice_proto_msgTypes,
	}.Build()
	File_companyservice_proto = out.File
	file_companyservice_proto_rawDesc = nil
	file_companyservice_proto_goTypes = nil
	file_companyservice_proto_depIdxs = nil
}
